[#75] Increase Windows sleep accuracy beyond 64 ticks per second
travisvroman/kohi pull request #126
Opened 2023-02-05 21:39 UTC by beewyka819

Addresses #75 

Increases the accuracy of the underlying timer device while sleeping in order to allow for more accurate thread sleeps on Windows. 

According to [](https://stackoverflow.com/a/19427182):

"Sleep() is accurate to the operating system's clock interrupt rate. Which by default on Windows ticks 64 times per second. Or once every 15.625 msec, as you found out. You can increase that rate, call timeBeginPeriod(10). Use timeEndPeriod(10) when you're done. You are still subject to normal thread scheduling latencies so you still don't have a guarantee that your thread will resume running after 10 msec. And won't when the machine is heavily loaded. Using SetThreadPriority() to boost the priority, increasing the odds that it will."

However instead of using a hardcoded value, this fix queries the minimum period of the underlying hardware timer via `timeGetDevCaps()` in the `clock_setup()` function.

Note that the sleep time does still seem to be quite unreliable, and it seems its because getting reliable timings on Windows can be notoriously difficult. Apparently using `Sleep()` is not really recommended for these kinds of applications. Would have to look further into that. I've seen some ideas floating around about combining sleeping with spinlocking as a potential way to increase accuracy (at the cost of more CPU usage).

2023-02-05 22:01 UTC, beewyka819 commented
Found a pretty accurate sleep function implementation here: [](https://blat-blatnik.github.io/computerBear/making-accurate-sleep-function/). Could potentially look into using something similar.

2023-02-16 04:03 UTC, beewyka819 commented
Update: I emailed the author after noticing some adjustments that could be made to his accurate sleep function, and he ended up following up by creating the following, more up-to-date blog post detailing a better sleep function: [https://blog.bearcats.nl/perfect-sleep-function/](https://blog.bearcats.nl/perfect-sleep-function/)

2023-02-16 04:28 UTC, beewyka819 commented
The blog mentions how newer versions of Windows 10/11 support timers, which can be preferable as they don't affect global state (changing scheduler period is global state. Setting this below 8 ms is known to cause significantly higher power usage on other applications, which I try to mitigate by only setting it when calling Sleep), however not sure it's wise to use them since it's only on these newer builds of Win 10/11.

2024-07-22 16:56 UTC, beewyka819 commented
Rebased to fix conflicts

2024-07-23 17:25 UTC, travisvroman requested changes
Thanks for submitting this! It looks great. Before I merge this though, would you mind merging it into the `v0.8.0` branch instead of main? Also if you wouldn't mind summarizing the change in the changelog file as well, that would be great.

2024-07-26 15:45 UTC, merged

2024-07-26 15:46 UTC, travisvroman commented
Switched branches and merged. Thank you!