memory feedback improvement
travisvroman/kohi pull request #221
Opened 2024-02-17 02:41 UTC by NotCampeur

Add field to track down how the memory evolved since last call of get_memory_usage_str.
Hope it helps.

2024-02-18 20:59 UTC, travisvroman requested changes
Thank you for submitting this! 

This looks pretty good, but would you mind changing this to merge into v0.7.0 instead of main?

2024-02-18 22:22 UTC, NotCampeur commented
The target branch is now v0.7.0.
Sorry I was unaware of the merge policy, thanks for letting me know!

2024-02-20 00:33 UTC, travisvroman approved these changes

2024-02-20 00:33 UTC, merged

2024-02-20 00:34 UTC, travisvroman commented
Thank you very much for this!